tagFormat: 'v${version}'
branches:
  - 'main'
  - name: 'beta'
    prerelease: true
  - name: 'alpha'
    prerelease: true

plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
  - '@semantic-release/changelog'
  - - '@semantic-release/git'
    - assets:
        - CHANGELOG.md
  - - '@semantic-release/exec'
    - publishCmd: |
        export CI_COMMIT_TAG="true"
        sbt 'set ThisBuild / version := "${nextRelease.version}"' ci-release
  - '@semantic-release/github'
