name: Build test and deploy
on:
  push:
    tags: ['*']
    branches-ignore:
      - 'autodelivery**'
      - 'bump-**'
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENCE'
      - 'README.md'
      - 'renovate.json'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: ['17.0.3']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Scala
        uses: actions/setup-java@v4.2.0
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: 'sbt'

      - name: Scalafmt
        run: sbt scalafmtCheckAll

      - name: Scalafix
        run: sbt 'scalafixAll --check'

      - name: WartRemover
        run: sbt wartremoverInspect

      - name: Plugin test
        run: sbt testPlugin

  publish:
    name: Publish
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta')
    steps:
      - name: Setup atedeg-bot
        id: atedeg-bot
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.ATEDEG_BOT_APP_ID }}
          private_key: ${{ secrets.ATEDEG_BOT_PRIVATE_KEY }}

      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          token: ${{ steps.atedeg-bot.outputs.token }}
          fetch-depth: 0

      - run: echo $PGP_SECRET | base64 --decode | gpg --batch --import
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

      - name: Release
        uses: atedeg/scala-release@v1.0.3
        with:
          java-version: "17.0.3"
          pgp-secret: ${{ secrets.PGP_SECRET }}
          pgp-passphrase: ${{ secrets.PGP_PASSPHRASE }}
          sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
          sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}
          github-token: ${{ steps.atedeg-bot.outputs.token }}